# SPDX-FileCopyrightText: 2026 James Harton
#
# SPDX-License-Identifier: Apache-2.0

if Code.ensure_loaded?(Igniter) do
  defmodule Mix.Tasks.BbSo101.Upgrade do
    @shortdoc "Brings joint limits back inside what the servos can actually do"
    @moduledoc """
    #{@shortdoc}

    Robots generated before this version declare joint limits the hardware
    cannot meet: 333 or 360 `degree_per_second`, and 2160
    `degree_per_square_second`. An STS3215 tops out near 300°/s, and clamps its
    acceleration register at 439.5°/s² however much more is written.

    That is no longer harmless. `BB.Servo.Feetech.Actuator` reads the
    acceleration register back at startup and refuses to run when the servo
    kept something other than what it was given, so an arm generated by an
    older installer will not boot.

    This rewrites `velocity` and `acceleration` in the `limit` block of every
    joint driven by a `BB.Servo.Feetech.Actuator`, leaving anything already
    inside the hardware's reach alone. Joints driven by something else are not
    touched, so a robot mixing servo families keeps the rest of its limits.

    Only `degree_per_second` and `degree_per_square_second` are rewritten,
    which is what the installer emits. A limit written in other units is
    reported rather than converted.
    """

    use Igniter.Mix.Task

    alias Sourceror.Zipper

    @driver BB.Servo.Feetech.Actuator

    # What an STS3215 actually manages. See `Mix.Tasks.BbSo101.Install`.
    @max_velocity_deg_s 300
    @max_acceleration_deg_s2 400

    @impl Igniter.Mix.Task
    def info(_argv, _parent), do: %Igniter.Mix.Task.Info{}

    @impl Igniter.Mix.Task
    def igniter(igniter) do
      {igniter, modules} =
        Igniter.Project.Module.find_all_matching_modules(igniter, fn _mod, _zipper -> true end)

      Enum.reduce(modules, igniter, &rewrite_module/2)
    end

    defp rewrite_module(module, igniter) do
      updater = fn zipper ->
        {:ok, Zipper.replace(zipper, Macro.prewalk(Zipper.node(zipper), &transform_joint/1))}
      end

      case Igniter.Project.Module.find_and_update_module(igniter, module, updater) do
        {:ok, updated} -> updated
        {:error, unchanged} -> unchanged
      end
    end

    defp transform_joint({:joint, meta, [name, do_block]} = node) when is_list(do_block) do
      with {:ok, body, wrapper} <- do_block_body(do_block),
           true <- feetech_driven?(body) do
        {:joint, meta, [name, rebuild_do(wrapper, rewrite_limits(body))]}
      else
        _ -> node
      end
    end

    defp transform_joint(other), do: other

    defp do_block_body([{{:__block__, _, [:do]}, body} = pair]), do: {:ok, body, {:block, pair}}
    defp do_block_body(do: body), do: {:ok, body, :plain}
    defp do_block_body(_), do: :error

    defp rebuild_do({:block, {key, _}}, body), do: [{key, body}]
    defp rebuild_do(:plain, body), do: [do: body]

    # Only joints this driver actually moves. A robot can mix servo families,
    # and these ceilings are one family's.
    defp feetech_driven?(body) do
      body
      |> statements()
      |> Enum.any?(fn
        {:actuator, _, args} -> Enum.any?(args, &mentions_driver?/1)
        _ -> false
      end)
    end

    defp mentions_driver?(ast) do
      {_, found?} =
        Macro.prewalk(ast, false, fn
          {:__aliases__, _, _} = alias_ast, acc ->
            {alias_ast, acc or Macro.expand(alias_ast, __ENV__) == @driver}

          node, acc ->
            {node, acc}
        end)

      found?
    end

    defp rewrite_limits(body) do
      map_statements(body, fn
        {:limit, meta, [inner]} when is_list(inner) ->
          case do_block_body(inner) do
            {:ok, limit_body, wrapper} ->
              {:limit, meta, [rebuild_do(wrapper, map_statements(limit_body, &clamp/1))]}

            :error ->
              {:limit, meta, [inner]}
          end

        other ->
          other
      end)
    end

    defp clamp({:velocity, meta, [sigil]}),
      do: {:velocity, meta, [clamp_sigil(sigil, "degree_per_second", @max_velocity_deg_s)]}

    defp clamp({:acceleration, meta, [sigil]}),
      do:
        {:acceleration, meta,
         [clamp_sigil(sigil, "degree_per_square_second", @max_acceleration_deg_s2)]}

    defp clamp(other), do: other

    defp clamp_sigil(
           {:sigil_u, meta, [{:<<>>, bin_meta, [content]}, mods]} = sigil,
           unit,
           ceiling
         )
         when is_binary(content) do
      with [value, ^unit] <- String.split(content, " ", parts: 2),
           {number, ""} <- Float.parse(value),
           true <- number > ceiling do
        {:sigil_u, meta, [{:<<>>, bin_meta, ["#{ceiling} #{unit}"]}, mods]}
      else
        _ -> sigil
      end
    end

    defp clamp_sigil(other, _unit, _ceiling), do: other

    defp statements({:__block__, _, stmts}), do: stmts
    defp statements(stmt), do: [stmt]

    defp map_statements({:__block__, meta, stmts}, fun),
      do: {:__block__, meta, Enum.map(stmts, fun)}

    defp map_statements(stmt, fun), do: fun.(stmt)
  end
end
